"""Parse a free-form unit expression (as generated by a model) into a Dimension.

Accepts symbols and long forms of registry units, invented lexemes supplied per call (singular
and plural), 'per' / '/' division, '·' '*' '-' ' ' multiplication, '^n', unicode superscripts,
'squared'/'cubed'/'to the fifth' postfix words and 'square'/'cubic' prefix words, and named
derived units (N, J, W, …).  Returns None when nothing parseable is found.
"""
from __future__ import annotations

import re
from typing import Iterable

from .dims import Dimension
from .units import Unit, get_registry

_SUP = {"⁰": "0", "¹": "1", "²": "2", "³": "3", "⁴": "4", "⁵": "5", "⁶": "6", "⁷": "7", "⁸": "8", "⁹": "9", "⁻": "-"}
_POST = {"squared": 2, "cubed": 3, "fourth": 4, "fifth": 5, "sixth": 6}
_PRE = {"square": 2, "cubic": 3}
_ORD = {"second": 2, "third": 3, "fourth": 4, "fifth": 5, "sixth": 6}


def _lexicon(extra: Iterable[Unit]) -> dict[str, Dimension]:
    reg = get_registry()
    lex: dict[str, Dimension] = {}
    for u in list(reg.units(invented=False)) + list(extra):
        for f in (*u.short, u.long_sg, u.long_pl):
            lex[f] = u.dim
            lex[f.lower()] = u.dim
        for sg, pl in u.translations.values():
            lex[sg] = u.dim; lex[pl] = u.dim
    return lex


def parse_unit_expression(text: str, extra_units: Iterable[Unit] = ()) -> Dimension | None:
    lex = _lexicon(extra_units)
    s = text.strip().split("\n")[0]
    s = "".join(_SUP.get(ch, ch) for ch in s)
    s = re.sub(r"^[\d.,\s]+", "", s)               # drop a leading number continuation
    s = re.split(r"[.,;:!?)(]", s)[0]              # first clause
    s = s.replace("·", " * ").replace("×", " * ").replace("*", " * ").replace("/", " / ")
    s = re.sub(r"(?<=[A-Za-z])-(?=[A-Za-z])", " * ", s)  # kg-cm
    s = re.sub(r"\^\s*", "^", s)
    s = re.sub(r"([A-Za-z])(\d)", r"\1^\2", s)          # mi3 -> mi^3
    toks = s.replace("^", " ^ ").split()
    dim = Dimension()
    sign = 1
    pending_pre = 1
    last: Dimension | None = None
    found = False
    i = 0
    while i < len(toks):
        t = toks[i]
        tl = t.lower()
        if tl in ("per", "/"):
            sign = -1; i += 1; continue
        if tl in ("*", "times", "x"):
            i += 1; continue
        if tl == "^" and i + 1 < len(toks) and last is not None:
            try:
                e = int(toks[i + 1]); i += 2
                dim = dim / (last ** 1) * (last ** e) if sign == 1 else dim * (last ** 1) / (last ** e)
                continue
            except ValueError:
                i += 1; continue
        if tl in _PRE:
            pending_pre = _PRE[tl]; i += 1; continue
        if tl in _POST and last is not None:
            e = _POST[tl]
            dim = dim / (last ** 1) * (last ** e) if sign == 1 else dim * (last ** 1) / (last ** e)
            i += 1; continue
        if tl == "to" and i + 2 < len(toks) and toks[i + 1].lower() == "the" and toks[i + 2].lower() in _ORD and last is not None:
            e = _ORD[toks[i + 2].lower()]
            dim = dim / (last ** 1) * (last ** e) if sign == 1 else dim * (last ** 1) / (last ** e)
            i += 3; continue
        if tl in ("the", "a", "an", "of", "power", "inverse", "1"):
            if tl == "inverse":
                sign = -1
            i += 1; continue
        d = lex.get(t) or lex.get(tl)
        if d is None:
            if found:
                break
            i += 1; continue
        found = True
        d = d ** pending_pre
        pending_pre = 1
        dim = dim * d if sign == 1 else dim / d
        last = d
        i += 1
    return dim if found else None


_KIND_TO_DIM = {"length": "L", "mass": "M", "time": "T", "electric current": "I", "temperature": "Th",
                "amount of substance": "N", "luminous intensity": "J"}


def invented_units_from_prompt(prompt: str) -> list[Unit]:
    """Recover invented units from in-context definitions ("A blork is a unit of length.",
    "Flarn is a basic physical quantity ...; it is measured in glorps (a glorp is the unit of flarn).")."""
    from .units import make_invented_unit, make_invented_base
    out: list[Unit] = []
    for m in re.finditer(r"\b[Aa]n? (\w+) is a unit of ([a-z ]+?)\.", prompt):
        lex, kind = m.group(1), m.group(2).strip()
        if kind in _KIND_TO_DIM:
            out.append(make_invented_unit(lex, Dimension({_KIND_TO_DIM[kind]: 1})))
        elif kind.startswith("another unit of "):
            pass
    for m in re.finditer(r"(\w+) is a basic physical quantity[^.]*measured in (\w+) \(an? (\w+) is the unit of", prompt):
        qname, _, ulex = m.groups()
        _, u = make_invented_base(qname.lower(), ulex, "X")
        out.append(u)
    return out


def generation_dimension_correct(gen: str, prompt: str, answer_dimension: str) -> bool | None:
    """True/False if a unit expression was parsed and matches/mismatches; None if nothing parsed."""
    d = parse_unit_expression(gen, invented_units_from_prompt(prompt))
    if d is None:
        return None
    return d == Dimension.parse(answer_dimension)
